// Generated by CoffeeScript 1.6.3
var findAssetUrl, path, stylesheetAssetUrlPattern;

path = require('path');

stylesheetAssetUrlPattern = /url\([\'\"]?([^\?\#\'\"\)]+)([^\'\"\)]*)[\'\"]?\)/gi;

findAssetUrl = function(manager, assetPath, cssPath, options) {
  var fullPath;
  if (manager.get(assetPath) != null) {
    return manager.get(assetPath);
  }
  fullPath = path.join(path.dirname(cssPath), assetPath);
  if (manager.get(fullPath) != null) {
    return manager.get(fullPath);
  }
  if (manager.make(assetPath, fullPath, options)) {
    return manager.get(assetPath);
  }
  return assetPath;
};

module.exports = function(manager, filename, content, options) {
  content = content.toString();
  content = content.replace(stylesheetAssetUrlPattern, function(src, assetPath, suffix) {
    var url;
    url = findAssetUrl(manager, assetPath, filename, options);
    return "url(\"" + url + suffix + "\")";
  });
  return content;
};
