// Generated by CoffeeScript 1.6.3
var Distribution, css;

Distribution = require('./Distribution');

css = require('./processors/css');

module.exports = function(options) {
  if (options == null) {
    options = {};
  }
  if (options.processors == null) {
    options.processors = {
      processors: {
        'text/css': css
      }
    };
  }
  return new Distribution(options);
};

module.exports.Distribution = Distribution;

module.exports.cssProcessor = css;
